### ISSUE TITLE
Creation typings to provide TypeScript support

### ISSUE THREAD

**Issue by blackyale** [sematext/logsene-js#13]
In order to import and use this within TypeScript projects @types are needed.

**Comment by otisg** [comment]
@AlejandroMoran Any chance you can submit a PR?

**Comment by blackyale** [comment]
@otisg Sorry I think I'm not able to do that due lack of knowledge, I have tried with an automatic generation with 'tsc' but it seems there's more work needed.

**Comment by adnanrahic** [comment]
Fixed in #16 :ok_hand:
