### ISSUE TITLE
Huge npm package size 

### ISSUE THREAD

**Issue by Urik** [sematext/logsene-js#20]
It seems like the YOUR_TOKEN_SIZE folder has been included in the bundle for some reason, resulting in package sizes of 195 MB.

**Comment by adnanrahic** [comment]
Thanks for letting me know. I'll look into this ASAP.

**Comment by adnanrahic** [comment]
I've fixed this issue with [version 1.1.73](https://www.npmjs.com/package/logsene-js/v/1.1.73). Thanks again for opening this issue.
