### ISSUE TITLE
Index conditional on message

### ISSUE THREAD

**Issue by erik-stephens** [sematext/logsene-js#5]
Not sure this is applicable for the logsene use case, but for indexing to private elasticsearch instances, it would be nice to allow the index name to be determined by data from the message.  The typical case would be for messages to be indexed into the appropriate time based index (eg foo-YYYY.MM.DD) based on the message timestamp.

Is that something you would be willing to support?  Ideally, I'd like to be able to define the index as a function to allow maximum flexibility.  Maybe something like this [around here](https://github.com/sematext/logsene-js/blob/master/index.js#L187)?

```
var _index = this.token;
if (typeof(_index) === 'function') {
  _index = _index(msg);
}
```

**Comment by megastef** [comment]
Sorry for the late reply. Possible, the standard mode uses following URL format https://server:port/index_or_logsene_token/_bulk -  this helps to identify wrong tokens (index names) in Logsene.  For the above function we would need to use /_bulk, means the URL must be customized as well. The current setUrl function tries to inject the index ("token" variable) in the URL:
https://github.com/sematext/logsene-js/blob/master/index.js#L102

Anyhow, some refactoring required for this function. We are open for PR's with additional functions, as long the default behavior remains (to avoid changes in tools using logsene-js already).

**Comment by megastef** [comment]
One step closer to this. Logsene-js uses /_bulk when the hostname does not include "logsene", so we can keep our default /TOKEN/_bulk and use /_bulk for any other Elasticsearch server. The constructor got a new options field useIndexInBulk: true/false to control the generation of the bulk request URL.  See updated README.

We well also add the capability to call a function "_index" if it is passed with the meta data, as suggested above. 

E.g.: 

```
logger.log('info', 'test _index function', {
          docSpecificIndexName: 'docSpecificIndexName',
          _index: function (msg) {
            return msg.docSpecificIndexName
          }
        })
```
